### ISSUE TITLE
Fails if <projectdir>/.nova directory does not exist

### ISSUE THREAD

**Issue by jfieber** [withoutfanfare/waypoint#15]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/113956/114438988-512c3100-9b7d-11eb-8d66-9ce9fb55bb5c.png">

It should create the `.nova` directory, but should only do so only upon creating the first journey so as to not litter projects with empty `.nova` folders.

**Comment by withoutfanfare** [comment]
Thanks! I'm part way through this already and it should be finished by this evening.

**Comment by jfieber** [comment]
👍 I can tell already that I'm going to really like this extension!
